### ISSUE TITLE
Once a column is selected for a property in the Mapping form, it cannot be removed

### ISSUE THREAD

**Issue by rogargon** [rogargon/data-mapping-tool-client#3]
If a column is selected for a property, it is just possible to change the column, but not to set it back to blank.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/1313870/226645154-641ba7e7-4292-4bdd-bf45-c1d0be1b2eaa.png">

**Comment by jorgechp** [comment]
Should be fixed on https://github.com/rhizomik/data-mapping-tool-client/pull/5

**Comment by rogargon** [comment]
Working now, thanks
